### ISSUE TITLE
Log in does not work when using wp-admin URL

### ISSUE THREAD

**Issue by dealancer** [pantheon-systems/wp-saml-auth#111]
This issue is similar to https://github.com/pantheon-systems/wp-saml-auth/issues/62.

I am using WP SAML Auth 0.3.5 and simpleSAMLphp library. I have following configuration overrides:

```
  if ( 'simplesamlphp_autoload' === $option ) {
    $value = ABSPATH . '/private/simplesamlphp/lib/_autoload.php';
  }
  if ( 'display_name_attribute' === $option ) {
    $value = 'displayName';
  }
  if ( 'first_name_attribute' === $option ) {
    $value = 'givenName';
  }
  if ( 'last_name_attribute' === $option ) {
    $value = 'sn';
  }
  if ( 'permit_wp_login' === $option ) {
    $value = false;
  }
  if ( 'get_user_by' === $option ) {
    $value = 'login';
  }
```

When `permit_wp_login` is turned off (`false`) following issue occurs.

Steps to reproduce it:

1. Go to `/wp-admin`
2. Log in using SAML
3. You are redirected to `https://<sitedomain>/wp-login.php?redirect_to=https%3A%2F%2F<sitedomain>%2Fwp-admin%2F&reauth=1` and following is shown:
<img width="425" alt="screen shot 2018-01-30 at 4 51 20 pm" src="https://user-images.githubusercontent.com/600216/35593434-e646c946-05dd-11e8-8bb4-3b72aaa6369a.png">
4. When you click `Back to GU WordPress MVP` you are visiting the home page of the website and user does not seem to be logged in.

If you remove `&reauth=1` from the URL in the browser and hit enter. You are successfully logged in.

**Comment by danielbachhuber** [comment]
Thanks for the report, @dealancer. I'll try to reproduce and debug when I have a moment.

**Comment by danielbachhuber** [comment]
@dealancer I'm not able to reproduce this:

![login](https://user-images.githubusercontent.com/36432/35887864-94115778-0b4a-11e8-9672-38766da1b0a2.gif)

Something I'm missing? Any other steps you can provide to reproduce this, or additional debugging you've done?

My config is essentially this:

```
add_filter( 'wp_saml_auth_option', function( $value, $option_name ){

	if ( 'connection_type' === $option_name ) {
		return 'simplesamlphp';
	}

	if ( 'simplesamlphp_autoload' === $option_name ) {
		return ABSPATH . '/private/simplesamlphp/lib/_autoload.php';
	}

	if ( 'permit_wp_login' === $option_name ) {
		return false;
	}

	if ( 'auth_source' === $option_name ) {
		return 'example-userpass';
	}
	return $value;
}, 11, 2 );
```

**Comment by dealancer** [comment]
@danielbachhuber 

Thanks for looking at this.

You logged in through `wp-login.php` - I don't have any problem with that too. Try logging in through `wp-admin`.

**Comment by danielbachhuber** [comment]
Thanks @dealancer — that was just the detail I needed. I've tagged a v0.3.6 release with the fix.

**Comment by dealancer** [comment]
@danielbachhuber thank you!

**Comment by dealancer** [comment]
@danielbachhuber it looks like I am still having this issue even after update to v0.3.6:

![login-fail](https://user-images.githubusercontent.com/600216/35988135-a478f2ce-0ccb-11e8-8b15-ab4058143c1b.gif)

**Comment by danielbachhuber** [comment]
Odd! I can't reproduce that.

Is it possible for you to debug the [change I made](https://github.com/pantheon-systems/wp-saml-auth/pull/112/files#diff-6263dbcace135f6a661e978c815c253fR246) to see why it's not applied in your case?

Here's an overview on what's going on:

* A request to `/wp-admin/` hits the `auth_redirect()`: https://github.com/WordPress/WordPress/blob/a1eb261cd1202c918a3e84b45fdf61f516ff3104/wp-includes/pluggable.php#L1003
* Shortly after, the `authenticate` filter is called which executes our `do_saml_authentication()` method: https://github.com/pantheon-systems/wp-saml-auth/blob/ebaa7a5d55b73f3af4d911861dcfcd5f27538e61/inc/class-wp-saml-auth.php#L202
* When the provider is SimpleSAMLPHP, SimpleSAMLPHP's `requireAuth()` method is called: https://github.com/pantheon-systems/wp-saml-auth/blob/ebaa7a5d55b73f3af4d911861dcfcd5f27538e61/inc/class-wp-saml-auth.php#L244

Alternatively, have you considered using the OneLogin bundled library? This is our preferred approach going forward

**Comment by dealancer** [comment]
@danielbachhuber after doing some debugging i figured out what is going on:

1. User visits `/wp-admin`
2. User is redirected to the IdP login form
3. User logs in
4.  User is redirected to `/wp-login.php?redirect_to=<encoded wp-admin url>
5.  User is redirected to to `/wp-admin`.
6.  User is redirected to `/wp-login.php?redirect_to=<encoded wp-admin url>&reauth=1`

It looks like something is going inside the WP. Following fix works for me:
```
			$this->provider->requireAuth(
				array(
					// Prevent WordPress from dropping the login cookie
					// when REQUEST_URI is /wp-admin/.
					'ReturnTo' => '/wp-login.php',
				)
			);
```

instead of current code: 

```
			$this->provider->requireAuth(
				array(
					// Prevent WordPress from dropping the login cookie
					// when REQUEST_URI is /wp-admin/.
					'ReturnTo' => str_replace( '&reauth=1', '', $_SERVER['REQUEST_URI'] ),
				)
			);
```

Not sure if it is a best solution, but at least if works.

**Comment by danielbachhuber** [comment]
@dealancer I wasn't able to reproduce the behavior using the steps you provided, oddly.

However, I think I have a more reliable approach in #113. Can you apply those changes in your environment and confirm the fix?

**Comment by dealancer** [comment]
@danielbachhuber that works for me, thank you!

**Comment by danielbachhuber** [comment]
👍 I've just tagged v0.3.7

Thanks again for your help @dealancer
