### ISSUE TITLE
Updates made to redirect logic since 0.3.6 has broken redirection after authentication

### ISSUE THREAD

**Issue by emmagard** [pantheon-systems/wp-saml-auth#114]
WordPress version: 4.9.4
wp-saml-auth version: 0.3.7
PHP version: 7.0

I am using the wp-saml-auth plugin in order to protect content on my site from non-authenticated users.

After updating the plugin to version 0.3.7 I am having issues with the redirection after authenticating:

-  A user is prompted to login to view content on a page. This is the structure of the link I use to send the user to the login page: `/wp-login.php?redirect_to=https://some-example-redirect-url`
- When on the login page a user can click the "Sign In" button, and the user can authenticate with the IdP. 
- Once authenticated, however, the user is sent back to the login page (`/wp-login.php?redirect_to=https://some-example-redirect-url`) . I expect the user to be sent to the redirect url (`https://some-example-redirect-url`)
- If the user clicks the "Sign In" button on the login page again, it is only then that the user will be redirected to the page from where they were originally prompted to log in (i.e. the `redirect_to` query var value).

I noticed this issue is resolved if I fallback to version 0.3.6 of the wp-saml-auth plugin.

**Comment by danielbachhuber** [comment]
Sorry about this, @emmagard :( I'll debug further when I have a moment.

**Comment by danielbachhuber** [comment]
Hi @emmagard,

This is now fixed in v0.3.8. Sorry for the inconvenience!

**Comment by emmagard** [comment]
Thanks, @danielbachhuber ! 0.3.8 is working as expected.
