### ISSUE TITLE
/wp-login.php redirection does not send user to /wp-admin post-authentication

### ISSUE THREAD

**Issue by emmagard** [pantheon-systems/wp-saml-auth#123]
After authenticating from a direct link of `/wp-login.php`, I am redirected back to `/wp-login.php` rather than `/wp-admin`.

As a WP SAML Auth user, I expect the post-authentication redirect behavior to mimic that of the WordPress login whereby a user who authenticates through a direct link of `/wp-login.php` will be redirected to `/wp-admin` after a successful authentication.

Consider adding a default value of `/wp-admin` for the `redirect_to` query parameter : https://github.com/pantheon-systems/wp-saml-auth/blob/master/inc/class-wp-saml-auth.php#L161 

Thanks!

**Comment by danielbachhuber** [comment]
Hi @emmagard,

Can you share more detail on how you've configured WP SAML Auth, and potentially a short screencast visually communicating the behavior you're seeing?

**Comment by danielbachhuber** [comment]
Yep, daniel@bachhuber.co is fine.

**Comment by danielbachhuber** [comment]
@emmagard Were you able to work this out?
