### ISSUE TITLE
Can't setup auth with custom Wordpress path

### ISSUE THREAD

**Issue by brodkin** [pantheon-systems/wp-saml-auth#132]
Hey there, not sure if this is a bug or a configuration problem, but...

I have the plugin configured to hit my Idp's (Keycloak) IDP initiated login URL:
```https://example.com/auth/realms/master/protocol/saml/clients/wordpress``` 

That redirect works as expected, but there is a URL mismatch:
```
Destination in response doesn't match the current URL. Destination is "https://example.com/wp/wp-admin", current URL is "https://example.com/wp".
```

This sorta makes sense because the Wordpress root is `https://example.com/wp`, but the homepage is at `https://example.com/`. I can simply tell Keycloak to use `https://example.com/wp` as the base URL and the error goes away, but then no login actually takes place.

Any ideas?

**Comment by danielbachhuber** [comment]
Hi @brodkin,

I've run into this once before but I don't recall the resolution. It'd be great to track it down and document in the README.

Can you share your configuration settings? In particular, I'm curious about these two values:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/36432/46286607-97c45d80-c534-11e8-84f7-01e12cb38cc0.png">

**Comment by scottmckenzie** [comment]
The only way I can get it to work on my site is with the assertionConsumerService url set to `home_url( '/wp-login.php' )`

@brodkin you probably need to set it to `home_url( '/wp/wp-login.php' )`

**Comment by danielbachhuber** [comment]
>  It'd be great to track it down and document in the README.

This was updated in #134
