### ISSUE TITLE
Allow population of attributes with $this->provider->getAttributesWithFriendlyName

### ISSUE THREAD

**Issue by defunctl** [pantheon-systems/wp-saml-auth#135]
Looking at the ability to utilizing https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L348

Perhaps a simple `apply_filters()` on https://github.com/pantheon-systems/wp-saml-auth/blob/master/inc/class-wp-saml-auth.php#L242 where we can override the method?

**Comment by danielbachhuber** [comment]
I'd be open to making `$attributes` generally filterable. Could we add it immediately after `wp_saml_auth_pre_authentication`?

**Comment by defunctl** [comment]
Whoops, I linked to the wrong method. That should work! As long as we pass the `$this->provider` object so we make use of that method, that would be wonderful.

**Comment by danielbachhuber** [comment]
> As long as we pass the `$this->provider` object so we can make use of that method, that would be wonderful.

Yep, that's fine.

**Comment by danielbachhuber** [comment]
Just tagged a v0.5.1 release with this.
