### ISSUE TITLE
Url structure issue with WP MultiSite 

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/wp-saml-auth#137]
Related to internal ticket 142154

User found the issue with simpleSAMLphp on WP Site Networks has conflicts in their naming convention for their url structure with the Site Network rewrites (the issue at hand from Pantheon's documentation concerning Shibboleth-SSO).

Does not work: 
https://example.com/simplesaml/module.php/core/frontpage_welcome.php

DOES work: 
https://example.com/simplesaml/module.php/core/frontpage_welcome.php/

Analysis:
The default WordPress Rewrite Rules are looking for urls that end with .php albeit to prevent odd directory access for php files directly.

User modified the code on the Simplesaml library, however that is not ideal as a workaround.

OneLogin is also not ideal, as the bindings for the different methods are strictly only HTTP-Redirect of which the authentication expects otherwise.

Possible Solution:
Is there any way that any URL ending with .php under /simplesaml/ can be excused by that catch-all rule configured on NGINX? This would resolve the multisite issue with SimpleSAMLPHP. SOME directories under simplesaml worked just fine. Anything ending in .php (even though its not a directory to a direct php file, its the way the urls are parsed by simplesamlphp's library).

**Comment by danielbachhuber** [comment]
> Is there any way that any URL ending with .php under /simplesaml/ can be excused by that catch-all rule configured on NGINX?

@carl-alberto It seems like this might need to be an infrastructure change, not a plugin change. Can you create an internal ticket for it?
