### ISSUE TITLE
Update onelogin to v3.1.1 for PHP 7.3 support

### ISSUE THREAD

**Issue by scottmckenzie** [pantheon-systems/wp-saml-auth#138]
I recently upgraded the PHP version to 7.3 and this caused login via wp-saml-auth to fail.  This was caused by the robrichards/xmlseclibs library required by onelogin/php-saml.

onelogin v3.1.1 includes version 3.0.3 of xmlseclibs which added PHP 7.3 support.
https://github.com/robrichards/xmlseclibs/releases/tag/3.0.3
https://github.com/onelogin/php-saml/releases/tag/3.1.1

**Comment by danielbachhuber** [comment]
Thanks for the report, @scottmckenzie ! I'll take a look at this next week.
