### ISSUE TITLE
REQUEST_URI contains arguments in non-Apache servers

### ISSUE THREAD

**Issue by gilzow** [pantheon-systems/wp-saml-auth#146]
See [this conversation ](https://wordpress.org/support/topic/doesnt-log-user-in-after-authentication/)for detailed information. 

TL;DR : in non-apache servers,`$_SERVER['REQUEST_URI']` contains both path components and arguments which causes the [test at line 271](https://github.com/pantheon-systems/wp-saml-auth/blob/master/inc/class-wp-saml-auth.php#L271) (in class-wp-saml-auth.php) to always evaluate to true. In this scenario a user is then returned to the login page after successfully authenticating, instead of the dashboard. 

Pull request submitted #145

**Comment by danielbachhuber** [comment]
Fixed by #145
