### ISSUE TITLE
google apps setup

### ISSUE THREAD

**Issue by rimavelez** [pantheon-systems/wp-saml-auth#150]
Is the Google Apps setup outlined here: https://pantheon.io/docs/wordpress-google-sso/ in addition to or in lieu of the default setup outlined here: https://wordpress.org/plugins/wp-saml-auth/#installation ?

I am seeing an error when trying to configure with the Google Apps setup here: https://pantheon.io/docs/wordpress-google-sso/ the error reads `Fatal error: Uncaught ArgumentCountError: Too few arguments to function {closure}(), 1 passed and exactly 2 expected`

My configuration is as follows:

```
add_filter( 'wp_saml_auth_option', function( $value, $option_name ) {
  // Use the OneLogin bundled library to connect to Google Apps
  if ( 'connection_type' === $option_name ) {
    return 'internal';
  }

  // Configuration details OneLogin uses to connect to Google Apps
  if ( 'internal_config' === $option_name ) {
    // ID for the service provider (e.g. your WordPress site)
    $value['sp']['entityId'] = 'urn:saml.sandbox.dev';
    // URL that Google Apps will redirect back to after authenticating.
    $value['sp']['assertionConsumerService']['url'] = 'https://saml.sandbox.dev';
    // ID provided for the Google Apps account.
    // 'abc123' will be something specific to your account.
    $value['idp']['entityId'] = 'https://accounts.google.com/o/saml2?idpid=t92lkw3o1';
    // URL that WordPress will redirect to for authentication.
    // 'abc123' will be a unique value specific to your account.
    $value['idp']['singleSignOnService']['url'] = 'https://accounts.google.com/o/saml2/idp?idpid=t92lkw3o1';
    // x509 certificate provided by Google Apps
    // Make sure to keep the file_get_contents because the entire certificate needs to be read into memory.
    $value['idp']['x509cert'] = file_get_contents( ABSPATH . 'wp-content/themes/renegade/private/GoogleIDPCertificate-wp-saml-auth.dev.pem' );
    return $value;
  }

  return $value;
});
```

Thank you for your help

**Comment by danielbachhuber** [comment]
Hi @rimavelez:

> Is the Google Apps setup outlined here: https://pantheon.io/docs/wordpress-google-sso/ in addition to or in lieu of the default setup outlined here: https://wordpress.org/plugins/wp-saml-auth/#installation ?

Should be in lieu of.

> I am seeing an error when trying to configure with the Google Apps setup here: https://pantheon.io/docs/wordpress-google-sso/ the error reads Fatal error: Uncaught ArgumentCountError: Too few arguments to function {closure}(), 1 passed and exactly 2 expected

> I am seeing an error when trying to configure with the Google Apps setup here: https://pantheon.io/docs/wordpress-google-sso/ the error reads Fatal error: Uncaught ArgumentCountError: Too few arguments to function {closure}(), 1 passed and exactly 2 expected

There's an error in your code. You'll need to pass a priority and argument count to the filter registration (see the `10, 2` in the following code snippet):

```php
add_filter( 'wp_saml_auth_option', function( $value, $option_name ) {}, 10, 2 );
```

Hope this helps!

**Comment by rimavelez** [comment]
Thank you very much for your help, that solved it.

I am running into another issue now. After using the one-click authentication, I am redirected back to my site successfully but I am not logged in. 

In SAML Chrome panel I see:

<saml2:AttributeStatement>
            <saml2:Attribute Name="first_name">
                <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">Firstname</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute Name="last_name">
                <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">Lastname</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute Name="user_login">
                <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">user@saml.dev</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute Name="user_email">
                <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">user@saml.dev</saml2:AttributeValue>
            </saml2:Attribute>
        </saml2:AttributeStatement>
        <saml2:AuthnStatement AuthnInstant="2019-05-12T13:17:00.000Z"
            SessionIndex=“_839f029qhd92h0j0j9hd83hd9”>
            <saml2:AuthnContext>
                <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml2:AuthnContextClassRef>
            </saml2:AuthnContext>
        </saml2:AuthnStatement>

I don’t know what urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified means but I am assuming that is the issue. Any insight would be much appreciated.
