### ISSUE TITLE
undefined index: placeholder on WP SAML Auth Settings page

### ISSUE THREAD

**Issue by msalle** [pantheon-systems/wp-saml-auth#177]
[class-wp-saml-auth-settings.php line 129](https://github.com/pantheon-systems/wp-saml-auth/blob/master/inc/class-wp-saml-auth-settings.php#L129) causes a warning when accessing the WP SAML Auth Settings page:
`Notice: Undefined index: placeholder in /var/lib/wordpress/wp-content/plugins/wp-saml-auth/inc/class-wp-saml-auth-settings.php on line 129`

Replacing with
`isset($arguments['placeholder']) ? esc_attr( $arguments['placeholder'] ) : "",`
would fix the warning, but it seems the `placeholder` argument is never used, so perhaps it's better to just remove it altogether from the code.

**Comment by danielbachhuber** [comment]
Thanks for the heads up, @msalle ! I've pushed a new release that removes the `placeholder` argument entirely.
