### ISSUE TITLE
Mapping multiple roles to users

### ISSUE THREAD

**Issue by nathansmonk** [pantheon-systems/wp-saml-auth#181]
I'm struggling to write a function that will map users from the AD role to a WordPress role.

I have $glass_roles which is an associative array, and the key is the AD role and the value is the WP role. It's possible, that a user could have multiple roles. I am not able to add multiple roles to a user.

```
global $glass_roles;
$glass_roles = array(
	'WP_Flagship-Administrator' => 'administrator',
	'WP_Flagship-Editor'        => 'editor',
);
function role_mapping( $user_args, $attributes ) {
	global $glass_roles;
	$groups = $attributes['http://schemas.microsoft.com/ws/2008/06/identity/claims/groups'];
	$roles = array_keys( $glass_roles );
	$role_match = array_intersect( $groups, $roles );
	$role_value = array_values( $glass_roles );
	$rolearray = array();

	foreach ($role_value as $role) {
		array_push($rolearray, $role);
	}
	
	$user_args['role'] = $rolearray;
	$user_args['display_name'] = $attributes['http://schemas.microsoft.com/identity/claims/displayname'][0];
	$user_args['first_name'] = $attributes['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname'][0];
	$user_args['last_name'] = $attributes['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname'][0];

	return $user_args;
}
add_filter( 'wp_saml_auth_insert_user', 'role_mapping', 10, 2 );
```

I seem to have to set the name properties of $user_args too, as without it they come through as an empty string.

i am certain there is a better way to do this, but I'm not able to find any supporting documentation. If someone is able to help me with the above, I'd be happy to write it up into the readme for others.

**Comment by danielbachhuber** [comment]
@nathansmonk Were you able to figure it out?

**Comment by nathansmonk** [comment]
@danielbachhuber Sorry, I realised how off the mark I was with this. My function now works. The only think that I'd like to improve is how the groups are gotten. Any insight into that based on the below:

```

global $glass_roles;
$glass_roles = array(
	'WP_Flagship-Administrator' => 'administrator',
	'WP_Flagship-Editor'        => 'editor',
);

function block_access( $ret, $attributes ) {
	global $glass_roles;
	$groups = $attributes['http://schemas.microsoft.com/ws/2008/06/identity/claims/groups'];
	$email_attribute = \WP_SAML_Auth::get_option( "user_email_attribute" );
	$AD_roles = array_keys( $glass_roles );
	$WP_roles = array_values( $glass_roles );
	$rolesearch = count( array_intersect( $groups, $AD_roles ) ) > 0;
	$role_match = array_intersect( $groups, $AD_roles );
	if ( empty( $groups ) || ! $rolesearch ) {
		return new WP_Error( 'unauthorized-group', "Sorry, you're not a member of an authorized group." );
	} else {
		$user = get_user_by( 'email', $email_attribute );
		$user_ID = $user->ID;
		$user_object = new WP_User( $user_ID );
		foreach ($WP_roles as $role) {
			$user_object->remove_role($role);
		}
		foreach ($role_match as $role) {
			$user_object->add_role($glass_roles[$role]);
		}
	}

	return $ret;

}
add_filter( 'wp_saml_auth_pre_authentication', 'block_access', 10, 2 );
```

**Comment by danielbachhuber** [comment]
> Sorry, I realised how off the mark I was with this. My function now works.

Cool, glad you were able to work it out!

> The only thing that I'd like to improve is how the groups are gotten. Any insight into that based on the below:

Sorry, it's hard to say without access to the actual document and the ability to debug. What you have seems alright to me though.

**Comment by nathansmonk** [comment]
Cool. I think others may benefit from this. Would you accept a PR that adds this to the readme?

**Comment by danielbachhuber** [comment]
@nathansmonk Thanks for the offer :) I think keeping the details in this issue is fine for now. The issue backlog is quite searchable.
