### ISSUE TITLE
Wodpress Multisite Network setup with GSuite SAML SSO

### ISSUE THREAD

**Issue by acremonezi** [pantheon-systems/wp-saml-auth#182]
Issue: infinite login loop, when click in "Sign In"

Bellow are the guides used to setup:
1. [WP SAML Auth setup process used](https://pantheon.io/docs/wordpress-google-sso)
2. [Wodpress Multisite Network setup process used](https://wordpress.org/support/article/create-a-network/)

Could you please clarify if the plugin work in a "Wodpress Multisite Network" ?
If so, what is the proper way to set it up?

Thanks in advanced.

**Comment by danielbachhuber** [comment]
Hi @acremonezi,

Sorry to hear you're having trouble!

It's hard to say what the "proper way to set it up" is, without seeing how you've configured it. Is this a site hosted on Pantheon?
