### ISSUE TITLE
Modify wordpress attributes that are not empty

### ISSUE THREAD

**Issue by Shinkaiser** [pantheon-systems/wp-saml-auth#185]
Hi again guys.

I think I will need your expertise once more.

Thanks to you I finally got the users created directly in WP when they don't exist by using SSO. They take the attributes from Google Apps and they are properly placed in WP (First Name, Last Name...)

The issue I have now occurs when I try to update these attributes. 

I change them at Google side, but when the user is logged back in to WP, these attributes are not updated. They remain the same as the first time when the user was created in WP.

Is there any way to prevent this? What would I need to check?

Many thanks in advance!

**Comment by danielbachhuber** [comment]
Hey @Shinkaiser,

If you want the attributes to sync as soon as you make the change in Google, you'd need to write some custom code that connects directly to Google.

If it's alright that the attributes sync when the user signs in again, here's an existing code snippet you could test and modify: https://github.com/pantheon-systems/wp-saml-auth#can-i-update-an-existing-wordpress-users-data-when-they-log-back-in

Hope this helps!
