### ISSUE TITLE
AzureAD Multifactor Issues

### ISSUE THREAD

**Issue by zchoate** [pantheon-systems/wp-saml-auth#187]
I have this implemented and requests work just fine except in cases where multi-factor authentication takes place with Windows Hello. We see an error "Authentication method 'X509, MultiFactor' by which the user authenticated with the service doesn't match the requested authentication method 'Password, ProtectedTransport'." This seems to be related to requestedAuthnContext default in OneLogin's PHP-SAML library. I went in and changed class-wp-saml-auth-options.php to include the security option `'requestedAuthnContext' => false,` in the settings array:
```
$settings = array(
			'connection_type' => 'internal',
			'internal_config' => array(
				'strict'  => true,
				'debug'   => defined( 'WP_DEBUG' ) && WP_DEBUG ? true : false,
				'baseurl' => $options['baseurl'],
				'sp'      => array(
					'entityId'                 => $options['sp_entityId'],
					'assertionConsumerService' => array(
						'url'     => $options['sp_assertionConsumerService_url'],
						'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
					),
				),
				'idp'     => array(
					'entityId'                 => $options['idp_entityId'],
					'singleSignOnService'      => array(
						'url'     => $options['idp_singleSignOnService_url'],
						'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
					),
					'singleLogoutService'      => array(
						'url'     => $options['idp_singleLogoutService_url'],
						'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
					),
					'x509cert'                 => $x509cert,
					'certFingerprint'          => $options['certFingerprint'],
					'certFingerprintAlgorithm' => $options['certFingerprintAlgorithm'],
				),
				'security'	=> array(
					'requestedAuthnContext' => false,
				),
			),
);
```
Is this something that can be fixed to specify nonstandard AuthnRequest types in the OneLogin library from the configuration of this plugin?

Here's a link to a good description of the same issue I was seeing: [https://github.com/getsentry/sentry/pull/17335](url)

I've also attached a screenshot of the error.
![aadlogin-error](https://user-images.githubusercontent.com/1207171/79166740-d4247b00-7db3-11ea-950e-1b6ecdd40886.png)

**Comment by danielbachhuber** [comment]
Thanks for the report, @zchoate.

> Is this something that can be fixed to specify nonstandard AuthnRequest types in the OneLogin library from the configuration of this plugin?

I'm not sure I follow. Did your specified change not fix the issue? OneLogin configuration values are meant to be passed in the manner you've described.

Related #157

**Comment by zchoate** [comment]
It did fix the issue. I wanted to make sure that was the best way to do it and how do I ensure that option stays the same when I update the plugin? 

I apologize for any ignorance in my questions, I'm relatively new to PHP and Wordpress.

**Comment by danielbachhuber** [comment]
Ah, no worries!

By editing `class-wp-saml-auth-options.php` directory, your changes will be blown away every time you update the plugin.

Instead, you should use a callback on the `wp_saml_auth_option` filter to override the specific options you'd like to configure.

There's a bit more detail with an example in the Installation instructions: https://github.com/pantheon-systems/wp-saml-auth#installation

You'd add your custom callback to your theme's `functions.php` file or a dedicated mu-plugin.

Here's a video explaining actions and filters in greater depth: https://www.ostraining.com/blog/wordpress/actions-filters/

There are also a number of tutorials on actions and filters across the web.

Happy to take any follow up questions you might have too.

**Comment by jonathandhn** [comment]
Hi, this is linked to : 
https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts75011-auth-method-mismatch

@zchoate I'm in the same disposition, could you help me to makes it works for 2FA enabled AD users ?

**Comment by olleharstedt** [comment]
Since this happened to be top google result for me, how do you know if the configuration `'requestedAuthnContext' => false` is safe?

**Comment by jonathandhn** [comment]
@olleharstedt it should, but If you are on AD with client using AD certificates instead of regular credentials, it will fail for them.

**Comment by melker** [comment]
We have the same problem.

Also MS suggests to remove the term: (just as @jonathandhn pointed out above)
https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts75011-auth-method-mismatch

Could you please remove the term or add a setting or something to be able remove that term from the sign in request in a controlled and future-proof manner?

**Comment by jonathandhn** [comment]
We were seeing Azure AD fail our SAML login with AADSTS75011 (“Authentication method ‘MultiFactor, Fido’ … doesn’t match requested authentication method ‘Password, ProtectedTransport’”). The culprit was that requestedAuthnContext was being disabled, but it lived outside the security block inside internal_config. Because of that placement, the underlying SAML library ignored the flag and still asked Azure AD for PasswordProtectedTransport, which conflicts with users authenticating via FIDO2/MFA.

Moving the security array inside internal_config fixed it:
```
'security' => array(
    'requestedAuthnContext' => false,
    'requestedAuthnContextComparison' => 'minimum',
),
```
With the option now in the correct spot (and leaving the comparison at minimum), Azure AD accepts the stronger methods and the SSO flow succeeds.

For a full demo config user Entra ID :
```
add_filter(
        'wp_saml_auth_option',
        function ( $value, $option_name ){
                $defaults = array (
                        'connection_type' => 'internal',
                        'internal_config'        => array(
                        'strict'       => true,
                        'debug'        => defined( 'WP_DEBUG' ) && WP_DEBUG ? true : false,
                        'baseurl'      => home_url(),
                        'sp'           => array(
                        'entityId' => 'urn:' . parse_url( home_url(), PHP_URL_HOST ),
                        'assertionConsumerService' => array(
                        'url'  => wp_login_url(),
                        'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
                        ),
                        ),
                        'idp'          => array(
                        // Required: Set based on provider's supplied value.
                        'entityId' => 'https://sts.windows.net/REDACTED-5d0e-468a-90de-REDACTED/',
                        'singleSignOnService' => array(
                        // Required: Set based on provider's supplied value.
                        'url'  => 'https://login.microsoftonline.com/REDACTED-5d0e-468a-90de-REDACTED/saml2',
                        'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
                        ),
                        'singleLogoutService' => array(
                        // Required: Set based on provider's supplied value.
                        'url'  => 'https://login.microsoftonline.com/common/wsfederation?wa=wsignout1.0',
                        'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
                        ),
                        // Required: Contents of the IDP's public x509 certificate.
                        // Use file_get_contents() to load certificate contents into scope.
                        'x509cert' => '',
                        // Optional: Instead of using the x509 cert, you can specify the fingerprint and algorithm.
                        'certFingerprint' => '81:1A:0F:DE:65:12:6C:2C:00:B7:05:61:94:74:23:35:15:A6:15:92:7C:AB:4D:1E:51:32:56:A1:7D:B5:98:99',
                        'certFingerprintAlgorithm' => 'sha256',
                        ),
                        'security'	=> array(
                        'requestedAuthnContext' => false,
                        'requestedAuthnContextComparison' => 'minimum',
                        ),
                        ),
                        'auto_provision'         => true,
                        'permit_wp_login'        => true,
                        'get_user_by'            => 'email',
                        'user_login_attribute'   => 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress',
                        'user_email_attribute'   => 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress',
                        'display_name_attribute' => 'http://schemas.microsoft.com/identity/claims/displayname',
                        'first_name_attribute'   => 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname',
                        'last_name_attribute'    => 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname',
                        'default_role'           => get_option( 'default_role' ),
                );
               $value = isset( $defaults[ $option_name ] ) ? $defaults[ $option_name ] : $value;
                return $value;
        },
        10,
        2
);
/**
 * Update user attributes after a user has logged in via SAML.
 */
add_action( 'wp_saml_auth_existing_user_authenticated', function( $existing_user, $attributes ) {
    $user_args = array(
        'ID' => $existing_user->ID,
    );
    foreach ( array( 'display_name', 'first_name', 'last_name' ) as $type ) {
        $attribute          = \WP_SAML_Auth::get_option( "{$type}_attribute" );
        $user_args[ $type ] = ! empty( $attributes[ $attribute ][0] ) ? $attributes[ $attribute ][0] : '';
    }
    wp_update_user( $user_args );
}, 10, 2 );
```
