### ISSUE TITLE
Honour SAML RelayState when it contains a preserved redirect_to containing wp_login_url

### ISSUE THREAD

**Issue by Maffsie** [pantheon-systems/wp-saml-auth#191]
I ran into the issue today where, when used in conjunction with IndieAuth (where WP-SAML-Auth acts as an SP and IndieAuth acts as an IdP), the `redirect_to` field is not being honoured.
The expected flow is:
* User visits https://indielogin.com and inputs their WP site URL
* User is redirected to https://their-site/wp-login.php?indieauth-state-values
* IndieAuth recognises the user is not logged in, and user is redirected to https://their-site/wp-login.php?redirect_to=(the indieauth-generated redirect)
* User clicks "Log in with SAML" and goes through the IdP login flow
* User is returned to https://their-site/wp-login.php?indieauth-state-values

The actual result is that, following the IdP flow, the user is instead taken to https://their-site/wp-admin

The problem is at line 248 of `inc/class-wp-saml-auth.php`: https://github.com/pantheon-systems/wp-saml-auth/blob/master/inc/class-wp-saml-auth.php#L248
The `RelayState` value is being silently dropped, as the IndieAuth redirect_to contains `wp_login_url()`.
Could this be changed to honour the redirect_to value under circumstances where wp-login would not be displaying (or performing) a login (as I imagine this code was introduced to prevent a login loop)? As a stopgap measure, on my own site I have tweaked this line to be:
```php
if ( $redirect_to && false === stripos( $redirect_to, 'action=wp-saml-auth' ) ) {
```

Thanks for all your hard work on this plugin!

**Comment by danielbachhuber** [comment]
Hey @Maffsie,

Thanks for the report. It looks like the origin of this conditional is https://github.com/pantheon-systems/wp-saml-auth/pull/103#issuecomment-347718732

> Could this be changed to honour the redirect_to value under circumstances where wp-login would not be displaying (or performing) a login (as I imagine this code was introduced to prevent a login loop)? As a stopgap measure, on my own site I have tweaked this line to be:

<del>I *think* your change is your fine. From that pull request (2 1/2 years ago!), it looks like I added the conditional to fix the failing integration test.</del>

I applied your change in #192 to see what would happen and the first test failed. Upon further diagnosis, I realized that the problem arises when `permit_wp_login=false`. 

Can you verify that 790a075 works as expected for you? If so, I'll get into a release next week.

**Comment by Maffsie** [comment]
Hi @danielbachhuber - thanks for the quick response! I tested the patch in question and it appears to work perfectly :)

**Comment by danielbachhuber** [comment]
@Maffsie Great 👌

**Comment by danielbachhuber** [comment]
Just tagged the release 🚢 🚢 🚢 

Thanks again!
