### ISSUE TITLE
autoprovision users works only for single site

### ISSUE THREAD

**Issue by msalle** [pantheon-systems/wp-saml-auth#197]
In the context of a multisite installation and using the autoprovisioning, the user will only be autoprovisioned in the first site they log in to. This happens because once logged in to a site and being autoprovisioned there, the user is an `$existing_user` in [class-wp-saml-auth.php#L323](https://github.com/pantheon-systems/wp-saml-auth/blob/master/inc/class-wp-saml-auth.php#L323).
As a result, if the new user then browses to a different subsite or logs out and then logs in to a different subsite, the user will be logged in (which works network-wide in wordpress) but will not become a user of those other subsites.

I would suggest to change the behaviour such that upon logging in to a subsite, the user gets autoprovisioned (and with the correct default roles) in *all* the subsites that have the wp-saml-auth plugin enabled. Since the set of sites may change, or because some users are already existing and member of some but not all sites, it would be good to also autoprovision an existing user that logs in to any wp-saml-auth-enabled site it isn't yet member of.

I have a patch that implements this behaviour, see https://github.com/msalle/wp-saml-auth/commit/fdfd2f1575579659ba605dd95b42f1fee292c330
Let me know if you are interested in a PR, and whether you like to see certain changes.

**Comment by danielbachhuber** [comment]
Thanks for the request, @msalle 

> I would suggest to change the behaviour such that upon logging in to a subsite, the user gets autoprovisioned (and with the correct default roles) in all the subsites that have the wp-saml-auth plugin enabled. Since the set of sites may change, or because some users are already existing and member of some but not all sites, it would be good to also autoprovision an existing user that logs in to any wp-saml-auth-enabled site it isn't yet member of.

I don't think this is functionality we'll include in the plugin for a couple of reasons:

1. It would unexpectedly change the plugin's behavior for existing users.
2. For multisite installations with a large number of sites, the code you've suggested will have negative performance implications.

You're welcome to publish what you have as a companion plugin on WordPress.org or GitHub though.

Hope this helps.

**Comment by msalle** [comment]
Hi Daniel,
thanks for the quick response. I understand your point and no, it's not really a problem for me since I'm maintaining a few other patches for our use case in any case.
I do wonder how you suggest that users should get autoprovisioned in other sites in a network once they're autoprovisioned in the first of these? Would you suggest to do it with a custom `add_action` for `wp_saml_auth_existing_user_authenticated` action? That can work of course, apart from the fact that users would still need to explicitly log in to each site separately (which turned out to be highly confusing for our users).
Best wishes,
Mischa

**Comment by danielbachhuber** [comment]
> I do wonder how you suggest that users should get autoprovisioned in other sites in a network once they're autoprovisioned in the first of these? Would you suggest to do it with a custom `add_action` for `wp_saml_auth_existing_user_authenticated` action? That can work of course, apart from the fact that users would still need to explicitly log in to each site separately (which turned out to be highly confusing for our users).

This is one approach, certainly.

Another approach would be to have some logic that assigns the user a role as soon as they visit the site. Here's an untested example:

```php
add_action(
	'template_redirect',
	function() {
		if ( is_user_logged_in()
			&& ! is_user_member_of_blog() ) {
			add_user_to_blog( get_current_user_id(), get_current_blog_id(), get_option( 'default_role' ) );
			wp_safe_redirect( '' );
			exit;
		}
	}
);
```

**Comment by msalle** [comment]
Thanks, yes that could work (although the performance penalty might actually be larger). I'll probably leave my code for our site as is but thanks for the hints and pointers.
