### ISSUE TITLE
Question on how to update/override values of a funtion using mu-plugin

### ISSUE THREAD

**Issue by yasvanth** [pantheon-systems/wp-saml-auth#198]
Hi,
Since I dont have much experience on wordpress and php, I am not sure how to update the values in a function using mu-plugin. 

I have filter to update settings on backend as suggested in #186 
<pre>
add_filter(
        'wp_saml_auth_option',
        function( $value ) {
                return $value;
        }
);
</pre>

Now I want to update values in function `wpsa_filter_option` so that the values remain constant during plugin upgrade. 
Below snippet  doesn't work. Any one has done this earlier with ther setting
<pre>
add_filter(
        'wpsa_filter_option',
        function ( $value, $option_name ){
                $defaults = array (
                        'connection_type' => 'simplesamlphp',
                        'simplesamlphp_autoload' => '/var/www/vhosts/dev.site/simplesamlphp/lib/_autoload.php',
                        'auth_source'            => 'default-sp',
                        'auto_provision'         => true,
                        'permit_wp_login'        => true,
                        'get_user_by'            => 'email',
                        'user_login_attribute'   => 'uid',
                        'user_email_attribute'   => 'mail',
                        'display_name_attribute' => 'display_name',
                        'first_name_attribute'   => 'first_name',
                        'last_name_attribute'    => 'last_name',
                        'default_role'           => get_option( 'default_role' ),
                );
               $value = isset( $defaults[ $option_name ] ) ? $defaults[ $option_name ] : $value;
                return $value;
        }
);
</pre>

Thanks,
Yash

**Comment by danielbachhuber** [comment]
Hey @yasvanth,

The filter name is `wp_saml_auth_option`. Here's a corrected version of your second code snippet:

```php
add_filter(
        'wp_saml_auth_option',
        function ( $value, $option_name ){
                $defaults = array (
                        'connection_type' => 'simplesamlphp',
                        'simplesamlphp_autoload' => '/var/www/vhosts/dev.site/simplesamlphp/lib/_autoload.php',
                        'auth_source'            => 'default-sp',
                        'auto_provision'         => true,
                        'permit_wp_login'        => true,
                        'get_user_by'            => 'email',
                        'user_login_attribute'   => 'uid',
                        'user_email_attribute'   => 'mail',
                        'display_name_attribute' => 'display_name',
                        'first_name_attribute'   => 'first_name',
                        'last_name_attribute'    => 'last_name',
                        'default_role'           => get_option( 'default_role' ),
                );
               $value = isset( $defaults[ $option_name ] ) ? $defaults[ $option_name ] : $value;
                return $value;
        }
);
```

**Comment by yasvanth** [comment]
Hi @danielbachhuber,

Thanks for your response, When I tried to add your filter, I get an error saying that 
`There has been a critical error on your website. Please check your site admin email inbox for instructions.`


<pre>
add_filter(
        'wp_saml_auth_option',
        function ( $value, $option_name ){
                $defaults = array (
                        'connection_type' => 'simplesamlphp',
                        'simplesamlphp_autoload' => '/var/www/vhosts/dev.site/simplesamlphp/lib/_autoload.php',
                        'auth_source'            => 'default-sp',
                        'auto_provision'         => true,
                        'permit_wp_login'        => true,
                        'get_user_by'            => 'email',
                        'user_login_attribute'   => 'uid',
                        'user_email_attribute'   => 'mail',
                        'display_name_attribute' => 'display_name',
                        'first_name_attribute'   => 'first_name',
                        'last_name_attribute'    => 'last_name',
                        'default_role'           => get_option( 'default_role' ),
                );
               $value = isset( $defaults[ $option_name ] ) ? $defaults[ $option_name ] : $value;
                return $value;
        }
);
</pre>

I have provided the content of the file where I add the filters
 `mu_plugins/wp-saml-auth-backend-config.php` 
<pre>
<?php
/* 
   Filter to configure saml setting
   in backend. 
*/
add_filter(
        'wp_saml_auth_option',
        function( $value ) {
                return $value;
        }
);
/* 
   Filter to override saml settings 
   for the plugin wp-saml-auth
*/
add_filter(
        'wp_saml_auth_option',
        function ( $value, $option_name ){
                $defaults = array (
                        'connection_type' => 'simplesamlphp',
                        'simplesamlphp_autoload' => '/var/www/vhosts/dev.site/simplesamlphp/lib/_autoload.php',
                        'auth_source'            => 'default-sp',
                        'auto_provision'         => true,
                        'permit_wp_login'        => true,
                        'get_user_by'            => 'email',
                        'user_login_attribute'   => 'uid',
                        'user_email_attribute'   => 'mail',
                        'display_name_attribute' => 'display_name',
                        'first_name_attribute'   => 'givenName',
                        'last_name_attribute'    => 'sn',
                        'default_role'           => get_option( 'default_role' ),
                );
               $value = isset( $defaults[ $option_name ] ) ? $defaults[ $option_name ] : $value;
                return $value;
        }
);
</pre>

Best,
Yash

**Comment by danielbachhuber** [comment]
Hi @yasvanth,

Sorry about that. You need to specify the number of callbacks too (2):

```php
add_filter(
        'wp_saml_auth_option',
        function ( $value, $option_name ){
                $defaults = array (
                        'connection_type' => 'simplesamlphp',
                        'simplesamlphp_autoload' => '/var/www/vhosts/dev.site/simplesamlphp/lib/_autoload.php',
                        'auth_source'            => 'default-sp',
                        'auto_provision'         => true,
                        'permit_wp_login'        => true,
                        'get_user_by'            => 'email',
                        'user_login_attribute'   => 'uid',
                        'user_email_attribute'   => 'mail',
                        'display_name_attribute' => 'display_name',
                        'first_name_attribute'   => 'first_name',
                        'last_name_attribute'    => 'last_name',
                        'default_role'           => get_option( 'default_role' ),
                );
               $value = isset( $defaults[ $option_name ] ) ? $defaults[ $option_name ] : $value;
                return $value;
        },
        10,
        2
);
```

**Comment by yasvanth** [comment]
@danielbachhuber ,
No luck, is it because I have two `add_filter` ?

**Comment by yasvanth** [comment]
@danielbachhuber, Thanks I made a mistake in `add_filter` added callback without `,`.
Everything works great.
Thanks for your help.

**Comment by danielbachhuber** [comment]
Great, glad to hear you were able to figure it out.
