### ISSUE TITLE
Add a filter for redirection

### ISSUE THREAD

**Issue by hadamlenz** [pantheon-systems/wp-saml-auth#200]
Pantheon has a fix for redirections on multisites.  this would be an awesome place to add a filter

https://pantheon.io/docs/shibboleth-sso#wordpress-multisite-issues

**Comment by hadamlenz** [comment]
```
$redirect_to = filter_input( INPUT_GET, 'redirect_to', FILTER_SANITIZE_URL );
$redirect_to = $redirect_to ? $redirect_to : $_SERVER['REQUEST_URI'];
$redirect_to = apply_filters( 'wp_saml_auth_redirect_to',  $redirect_to );
$provider->login( $redirect_to );
```

**Comment by danielbachhuber** [comment]
Hi @hadamlenz,

It looks like that suggestion is pretty old, and I'm not sure what it was originally trying to fix: https://github.com/pantheon-systems/documentation/pull/4592

Is there a specific problem I can help you address?

**Comment by hadamlenz** [comment]
This would allow for programatic control over where the user is redirected after authentication.

In my case, on a multisite, without this "fix" we are always redirected back to the root site's dashboard.  With this we could send them to a subsite and user experience would be similar to what a user would normally do when logging in without the plugin.

In the case of that ticket, the bundled lib (onelogin) did not provide enough features to match simplesaml.  If it does, more effort needs to be given to documenting how that works.  The answers that pantheon support provides continually [relate back to this answer](https://pantheon.io/docs/shibboleth-sso#wordpress-multisite-issues) even when the plugin is not activated.

**Comment by danielbachhuber** [comment]
> This would allow for programatic control over where the user is redirected after authentication.
> 
> In my case, on a multisite, without this "fix" we are always redirected back to the root site's dashboard. With this we could send them to a subsite and user experience would be similar to what a user would normally do when logging in without the plugin.

Ah, ok. Want to submit a pull request that adds a `wp_saml_auth_redirect_to` filter to both implementations?

**Comment by hadamlenz** [comment]
sure thing

**Comment by hadamlenz** [comment]
we've figured out how to do this without the need to make this change.

**Comment by jithujoseph** [comment]
@hadamlenz Would you mind sharing how you resolved this? Experiencing the same issue and could use some help, if you still remember how this was solved. Thanks!
