### ISSUE TITLE
Capture Referer in Cookie or via SAML flow to be used in redirect

### ISSUE THREAD

**Issue by zampettim** [pantheon-systems/wp-saml-auth#209]
When a user is redirected to the wp-login.php page because they encountered a protected page, we want to be able to capture that information and then after the SAML authentication has completed, have a way to redirect them to the page they were trying to access. I don't see way to do that as far as I can tell.

Is there an ability to do that, via hooks or filters or some other mechanism?

**Comment by danielbachhuber** [comment]
Hi @zampettim:

> When a user is redirected to the wp-login.php page because they encountered a protected page, we want to be able to capture that information and then after the SAML authentication has completed, have a way to redirect them to the page they were trying to access. I don't see way to do that as far as I can tell.

In your code that redirects from the the protected page to wp-login.php, if you include the original protected page in `redirect_to` query parameter, the value will be passed through to your SAML provider, and then back from the SAML provider to WordPress.

Here's some untested code you could build from:

```php
wp_safe_redirect(
	add_query_arg(
		'redirect_to',
		rawurlencode( home_url( $GLOBALS['wp']->request ) ),
		wp_login_url()
	)
);
```

Hope this helps!
