### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp-saml-auth#234]
An issue to track formal PHP 8 support.

**Comment by danielbachhuber** [comment]
We'll need to drop PHP < 7.3 support in order to update OneLogin PHP SAML: https://github.com/onelogin/php-saml/releases/tag/4.0.0

**Comment by jonathandhn** [comment]
Plugin 1.2.1 with lsphp 8.0.2 to Google workplace with SAML2 without certificat but with footprint of it : It's works. Well done !

**Comment by patschi** [comment]
I was about setting up WP-SAML-Auth on my Wordpress instance, however came across an issue [already reported in the Wordpress Support forums](https://wordpress.org/support/topic/wp-saml-auth-wasnt-able-to-find-the-simplesaml_auth_simple-class-please-check/), and then found this GitHub issue.

As [PHP 7.2 is already EOL and unsupported](https://www.php.net/eol.php) and [PHP 7.3 is already out of active-support with only 3 months of security support left](https://www.php.net/supported-versions.php) I think it's a good time going forward and dropping < PHP 7.3, to allow PHP 8.0 compatibility. Especially as PHP 8.1 is already in the works.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @patschi! I'll run this up the flag pole.

**Comment by patschi** [comment]
Hi @danielbachhuber, I know that asking for updates is kind of unpolite. But is there any news in dropping 7.x support and upgrading dependencies to fully support 8.x? PHP 7.4 is now out of active support since about 2 weeks, so I think it would be a good time to change the minimum required PHP version.

**Comment by danielbachhuber** [comment]
@patschi No worries! Squeaky wheel gets the grease 😄 

I'll ask for approval to increase the minimum supported PHP version to 7.4. If I get approval, this is something we can do in the new year.
