### ISSUE TITLE
Is it possible to support multiple IdP?

### ISSUE THREAD

**Issue by lithiumlab** [pantheon-systems/wp-saml-auth#246]
Is is possible to support multiple IdP.
Right now the settings page or php filter allows for one set of iDP to be set.
Is is possible to support more than one?

**Comment by danielbachhuber** [comment]
Hey @lithiumlab,

Thanks for the question!

WP SAML Auth doesn't support multiple IdPs. We don't have any plans to support this, unfortunately.
