### ISSUE TITLE
Change default from simplesamlphp to onelogin or make it UI configurable

### ISSUE THREAD

**Issue by cweagans** [pantheon-systems/wp-saml-auth#250]
I'm not too thrilled about the idea of installing simplesamlphp ever again :)

Could the default be changed to `onelogin` instead? Or maybe make the default a little more nuanced -- maybe if simplesamlphp actually exists in the place you expect it to, then automatically switch to simplesamlphp, but otherwise use onelogin (and then let users override the default behavior via the existing configuration mechanism).

Alternatively, if there were a UI option to switch this setting, it wouldn't be that big of a deal.

**Comment by danielbachhuber** [comment]
Hey @cweagans 👋 

> I'm not too thrilled about the idea of installing simplesamlphp ever again :)

I totally get where you're coming from 😄 

> Could the default be changed to `onelogin` instead?

I considered this way back when I originally implemented it. However, I didn't have any great ideas around maintaining backwards compatibility for everyone who already had it installed. We opted for instead communicating that OneLogin is the recommended authentication bridge, unless you have some specific need for SimpleSAMLphp.

> Or maybe make the default a little more nuanced -- maybe if simplesamlphp actually exists in the place you expect it to, then automatically switch to simplesamlphp, but otherwise use onelogin (and then let users override the default behavior via the existing configuration mechanism).
> 
> Alternatively, if there were a UI option to switch this setting, it wouldn't be that big of a deal.

If you haven't yet filtered `wp_saml_auth_option` in your codebase, there's a Settings -> WP SAML Auth page where you can configure the OneLogin library:

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/36432/124638866-53cab980-de40-11eb-92fa-b593c9689fb5.png">

Does this answer your questions?

**Comment by cweagans** [comment]
Yeah, I found that. I ended up getting everything working, but it wasn't immediately clear if that page was to configure whatever backend was active or if it only applied to the onelogin toolkit. The only thing that was missing was an endpoint that shows the SP metadata. Some IdPs can auto-configure the SP based on metadata served from some URL (and some SPs can auto-configure based on IdP metadata exposed on some URL - could be a nice experience for this plugin: basically just plug in the URL to the IdP metadata and auto-configure the rest).

Great work on the plugin, by the way -- it was a very smooth experience all things considered.

**Comment by danielbachhuber** [comment]
Thanks!

> Some IdPs can auto-configure the SP based on metadata served from some URL (and some SPs can auto-configure based on IdP metadata exposed on some URL - could be a nice experience for this plugin: basically just plug in the URL to the IdP metadata and auto-configure the rest).

This sounds related to https://github.com/pantheon-systems/wp-saml-auth/issues/87

We'll keep that in mind for the next round of feature development.
