### ISSUE TITLE
PHP Notice Undefined index: sessionIndex 

### ISSUE THREAD

**Issue by bananastalktome** [pantheon-systems/wp-saml-auth#256]
In the latest 1.2.4 version of the plugin, I'm getting the notice `PHP Notice Undefined index: sessionIndex` in my logs when logging out. The full trace is as follows:

    wp-content/plugins/wp-saml-auth/inc/class-wp-saml-auth.php:201 WP_SAML_Auth::action_wp_logout
    wp-includes/class-wp-hook.php:292 WP_Hook::apply_filters
    wp-includes/class-wp-hook.php:316 WP_Hook::do_action
    wp-includes/plugin.php:484 do_action
    wp-includes/pluggable.php:633 wp_logout
    wp-login.php:668 [main]

It looks like the most recent commit (https://github.com/pantheon-systems/wp-saml-auth/commit/c72d545421598d9f016c8e0d66b852d47d89a561) added https://github.com/pantheon-systems/wp-saml-auth/blob/c72d545421598d9f016c8e0d66b852d47d89a561/inc/class-wp-saml-auth.php#L186-L190 which creates `sessionId` as the key in `$args`, but in https://github.com/pantheon-systems/wp-saml-auth/blob/c72d545421598d9f016c8e0d66b852d47d89a561/inc/class-wp-saml-auth.php#L197-L202 references `sessionIndex`.

**Comment by danielbachhuber** [comment]
@bananastalktome Yarg, sorry about that :(

The original index key should be `sessionIndex`. Want to submit a PR for that and I'll push out a new release?
