### ISSUE TITLE
Redirected to /srv/bindings/<longstring>/code/wp-login.php?action=simplesamlphp

### ISSUE THREAD

**Issue by larcher** [pantheon-systems/wp-saml-auth#29]
First some background

1. WP site Running on Pantheon
2. SimpleSAMLphp installed in `~/code/private/simplesamlphp-x.y.z/`  
with a symlink in `~/code/simplesaml/` pointing to `~/code/private/simplesamlphp-x.y.z/www`
3. WP SAML Auth plugin and WP Native PHP installed (in `~/code/wp-content/plugins/`) and active
4. Tiny custom plugin for configuring WP SAML Auth installed in `~/code/wp-content/mu-plugins/wp-saml-auth-config.php` 

Here's what happens

1. Visit `/wp-login.php`
2. Click the "one-click authentication" "Sign In" button  
  ( goes to `/wp-login.php?action=simplesamlphp`)
3. SimpleSAMLphp kicks in and sends me off to our organization's SSO system,  
and here's the problem: when SSP redirects to our IdP, the URL it includes in the `RelayState` parameter, the URL to come back to, is something like:  
`https://sitename.pantheonsite.io//srv/bindings/<biglongstring>/code/wp-login.php?action=simplesamlphp` 
4. So I log into our SSO, and get redirected back to that URL, and get a 404.

I followed the SSP code, starting with `SimpleSAML_Auth_Simple::requireAuth` (called from `do-saml-authentication()` in  `class-wp-saml-auth.php`).  Because no return URL is specified when calling `requireAuth`, SSP tries to figure out the return URL .. and it eventually calls `\SimpleSAML\Utils\HTTP::getSelfURL()` which is what returns the problematic `/srv/bindings/....` URL.   

My fix was to have WP SAML Auth specify a `ReturnTo` URL when calling `requireAuth` (PR coming soon). It works for me, but I'd like to try to run it through the tests too.

**Comment by danielbachhuber** [comment]
> I followed the SSP code, starting with SimpleSAML_Auth_Simple::requireAuth (called from do-saml-authentication() in class-wp-saml-auth.php). Because no return URL is specified when calling requireAuth, SSP tries to figure out the return URL .. and it eventually calls \SimpleSAML\Utils\HTTP::getSelfURL() which is what returns the problematic /srv/bindings/.... URL.

I wonder if this is a SimpleSAMLphp config issue. Did you set [baseurlpath](https://github.com/pantheon-systems/wp-saml-auth/blob/master/bin/fixtures/config.php.additions#L22) in config.php?

**Comment by larcher** [comment]
Yeah, I have this in my config array:
`'baseurlpath'           => 'https://'. $host .'/simplesaml/'`

If this helps, the value of `SCRIPT_FILENAME` from inside that `getSelfURL` looked like this:
`SCRIPT_FILENAME=/srv/bindings/<lotsoflettersandnumbers>/code//wp-login.php`

I wonder if that double slash is causing problems?  Not sure where that'd be coming from though.

**Comment by danielbachhuber** [comment]
@larcher I'm going to tag team with @stevector next week to see if we can help debug this in a multidev environment.

**Comment by stevector** [comment]
Sorry for the delayed response. I was out at the end of last week. I can dig in to this issue later today or tomorrow.

**Comment by stevector** [comment]
@larcher Can you give me the id of the site you are working on? I'd like to clone your code base to understand the config you have.

**Comment by larcher** [comment]
@stevector sure, ID according to terminus is `11658964-9664-4dc1-aae5-211bdecb2fe7` - it's the dev environment. 

Thanks for taking a look!

**Comment by stevector** [comment]
There's as a bug in SimpleSAMLphp 1.14.5 that was fixed in 1.14.6. https://github.com/simplesamlphp/simplesamlphp/issues/418

I've opened PRs to test the idea that this bug is the source of the problem:

- https://github.com/pantheon-systems/wp-saml-auth/pull/33
- https://github.com/pantheon-systems/wp-saml-auth/pull/32

**Comment by stevector** [comment]
The test for 1.14.5 fails in the way I would expect (double slash and site UUID included) https://circleci.com/gh/pantheon-systems/wp-saml-auth/97

1.14.6 fails differently. It has a port included in the url that is redirected back to. I'll keep digging. The solution may be what you found @larcher, that simply setting the URL to use for redirection is better than deriving it.

**Comment by stevector** [comment]
Yeah, this file assumes that if SERVER_PORT is not 443 then you must want the port in the the URL. And we don't.

https://github.com/simplesamlphp/simplesamlphp/blob/e8ee8c83ef535273428f4c330107415b8ac6050d/lib/SimpleSAML/Utils/HTTP.php#L103

https://github.com/simplesamlphp/simplesamlphp/blob/e8ee8c83ef535273428f4c330107415b8ac6050d/lib/SimpleSAML/Utils/HTTP.php#L585

**Comment by stevector** [comment]
I merged https://github.com/pantheon-systems/wp-saml-auth/pull/35 yesterday. @larcher, I'm going to close this issue. Please re-open if you further problems arise.
