### ISSUE TITLE
Problem to authenticate with WordPress MU subsites since latest simplesamlphp

### ISSUE THREAD

**Issue by provosta99** [pantheon-systems/wp-saml-auth#316]
We upgraded our simplesamlphp to 1.19.7 to support PHP8. We now have redirect to login after authentication on Wordpress multisite for subsites. Only the network Wordpress login is still working. Since entityID are mandatory now, we had to add this line to obtain correct metadata 
'entityID' => 'https://'.$_SERVER['HTTP_HOST'].'/simplesaml/module.php/saml/sp/metadata.php/default-sp'

Metadata returned for sites are good. I'm also able to retreive attribute at the simplesaml level for every sites. 

How i can fix this issue?

**Comment by rwagner00** [comment]
Thanks for the report, I'm creating an issue for this now. To clarify, is authentication working and then redirecting you to the login page, or is it not working at all and simply redirecting you back to the login page without logging you in?

**Comment by provosta99** [comment]
Authentication is working, i'm able to authenticate on the IDP but after that iM redirected to the page with the login button.
Thank you!

**Comment by rwagner00** [comment]
Got it. I'll add this information to the ticket and get this in the queue. Thanks for the report!

**Comment by provosta99** [comment]
Problem solved, we had to add this line in the wp_config.php file of the Wordpress
define( 'COOKIE_DOMAIN', false );

**Comment by rwagner00** [comment]
Got it, thank you for letting us know! Closing this issue for now.
