### ISSUE TITLE
Consider updating tests to use HEAD of SimpleSAMLphp rather than set version number

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/wp-saml-auth#34]
It now appears that https://github.com/pantheon-systems/wp-saml-auth/issues/29 was caused by a regression in SimpleSAMLphp. I think we should consider switching our tests to use whatever are the latest commits in SimpleSAMLphp rather than a fixed release. Doing so can allow us to catch regressions as soon as they happen.

Over in https://github.com/pantheon-systems/search_api_pantheon I use the HEAD of Search API modules for this reason.

**Comment by danielbachhuber** [comment]
> I think we should consider switching our tests to use whatever are the latest commits in SimpleSAMLphp rather than a fixed release. Doing so can allow us to catch regressions as soon as they happen.

👍

**Comment by danielbachhuber** [comment]
Also probably impetuous to run the test suite nightly, so we can catch when SimpleSAMLphp starts to fail.

**Comment by stevector** [comment]
> run the test suite nightly, so we can catch when SimpleSAMLphp starts to fail.

Already happening with Circle. I suppose we should do the same with Travis.

**Comment by danielbachhuber** [comment]
> I think we should consider switching our tests to use whatever are the latest commits in SimpleSAMLphp rather than a fixed release. Doing so can allow us to catch regressions as soon as they happen.

Going with the latest stable release so we can get the heads up with SimpleSAMLphp is broken, but aren't necessarily spammed with failing master notices.
