### ISSUE TITLE
Plugin installed from WordPress repository doesn't match Github code

### ISSUE THREAD

**Issue by jon-heller** [pantheon-systems/wp-saml-auth#54]
Hello again,

When attempting to use this plugin, after authentication we were being redirected to port 18319. Looking at the code in `class-wp-saml-auth.php` we noticed line 132 was

```
$this->provider->requireAuth();
```

However in the Github repository it was 

```
$this->provider->requireAuth( array( 'ReturnTo' => $_SERVER['REQUEST_URI'] ) );
```

Updating the code to that version fixed our issue, so it just seems like the WordPress code repository might need that same update.

**Comment by danielbachhuber** [comment]
> so it just seems like the WordPress code repository might need that same update.

Yep, this is the case. v0.2.0 wasn't ever released. I'll get it released now.

**Comment by danielbachhuber** [comment]
🚢 🚢 🚢
