### ISSUE TITLE
IdP-First authentication?

### ISSUE THREAD

**Issue by sbarre** [pantheon-systems/wp-saml-auth#59]
Does this plugin support IdP-First authentication?  

If so, what would the Assertion Consumer Service URL be that the IdP would post login requests to?

**Comment by danielbachhuber** [comment]
Hi @sbarre,

This plugin integrates with a SimpleSAMLphp installation, which performs the actual SAML authentication. It [appears SimpleSAMLphp supports IdP-First](https://simplesamlphp.org/docs/1.8/simplesamlphp-idp-more#section_4).

I don't have any personal experience with IdP-First though. I'll ask inside Pantheon to see if anyone can weigh in with more detail.

**Comment by joshkoenig** [comment]
This does work. Under the current setup, you will use a path like so in your IdP config:

`https://your-wordpress-site.com/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp`

However, this does beg a number of questions about documentation.
