### ISSUE TITLE
permit_wp_login not works

### ISSUE THREAD

**Issue by uftang88** [pantheon-systems/wp-saml-auth#62]
Hi guys,
When I change "permit_wp_login" => false, I have redirected to my idp login page, have success login but after them I cant login to wp-admin, all time I redirected to 
"wp-login.php?redirect_to=https%3A%2F%2Fblog_name%2Fwp-admin%2F&reauth=1"
When I set permit_wp_login => true and iniciate saml login by click on button - all works fine...can you please help?

**Comment by danielbachhuber** [comment]
Hi @uftang88,

I'm not sure I follow the issue you're reporting. Any chance you can share a screencast (or screenshots) documenting the flow?

**Comment by uftang88** [comment]
Hi @danielbachhuber 
When I change permit_wp_login => false
http://prnt.sc/esns4w
After them I try to login in wp-admin...I have redirected to my idp login page
http://prnt.sc/esnsol
After successful auth I've redirected to this page and can't access wp-admin
http://prnt.sc/esnthf

**Comment by danielbachhuber** [comment]
Thanks for the screenshots, @uftang88. I see what you're referring to now.

I need to set up a test environment to see if I can reproduce. I'm traveling this week, so I won't be able to get to it until next week.

If you want to try to track this down yourself, I'd suggest debugging the logic in this: https://github.com/pantheon-systems/wp-saml-auth/blob/master/inc/class-wp-saml-auth.php#L112-L126

```
/**
 * Check if the user is authenticated against the SimpleSAMLphp instance
 */
public function filter_authenticate( $user, $username, $password ) {
	$permit_wp_login = self::get_option( 'permit_wp_login' );
	if ( is_a( $user, 'WP_User' ) && $permit_wp_login ) {
		return $user;
	}
	if ( ( ! $permit_wp_login && empty( $_GET['loggedout'] ) ) || ( ! empty( $_GET['action'] ) && 'simplesamlphp' === $_GET['action'] ) ) {
		$user = $this->do_saml_authentication();
	}
	return $user;
}
```

It could be that this logic doesn't work as expected when `! $permit_wp_login`.

**Comment by uftang88** [comment]
Hi @danielbachhuber , I have tried to debug but I'm a not php-dev and it's very hard for me..

**Comment by uftang88** [comment]
@danielbachhuber I think issue with account permissions...when $permit_wp_login => false; user not received correct permissions

**Comment by danielbachhuber** [comment]
@uftang88 I'm unable to reproduce this issue. Here's a screencast of what I see: http://quick.as/2Gbfbjgj

I'm using these configuration settings:

```
$defaults = array(
    'simplesamlphp_autoload' =>  $_SERVER['DOCUMENT_ROOT'] . '/private/simplesamlphp/lib/_autoload.php',
    'auth_source'            => 'example-userpass',
    'auto_provision'         => true,
    'permit_wp_login'        => false,
    'get_user_by'            => 'email',
    'user_login_attribute'   => 'uid',
    'user_email_attribute'   => 'mail',
    'display_name_attribute' => 'display_name',
    'first_name_attribute' => 'first_name',
    'last_name_attribute' => 'last_name',
    'default_role'           => get_option( 'default_role' ),
);
```

Few follow-up questions:

1. Do your configuration settings differ from the ones I've listed?
2. What role does your WordPress user have?
3. Was this WordPress user provisioned in the authentication process, or an existing user?

**Comment by uftang88** [comment]
Hi @danielbachhuber 
1. i have used 'user_login_attribute'   => 'sAMAccountName'
2. administrator
3. for the existen user

**Comment by danielbachhuber** [comment]
@uftang88 I managed to reproduce this while working on something else.

We'll have a fix out in the next release. In the interim, you can apply the change in b65f232

**Comment by danielbachhuber** [comment]
Another report in https://wordpress.org/support/topic/reauth1

**Comment by oebeledrijfhout** [comment]
I'm on 0.3.1 and still experiencing the same or a similar issue: when I login from the wp-admin/ URL, I'm redirected to http://www.example.com/wp-login.php?redirect_to=http%3A%2F%2Fwww.example.com%2Fwp-admin%2F&reauth=1

when I login from the http://www.example.com/wp-login.php URL, everything works fine.

**Comment by dealancer** [comment]
+1 same issue as @oebeledrijfhout

**Comment by dealancer** [comment]
I think the problem is in `reauth` parameter (`&reauth=1`) when it is removed everything works as expected.

**Comment by danielbachhuber** [comment]
@dealancer Can you open a new issue with a full report and sufficient reproduction steps? Thanks

**Comment by dealancer** [comment]
@danielbachhuber sure: https://github.com/pantheon-systems/wp-saml-auth/issues/111
