### ISSUE TITLE
Group to role mapping

### ISSUE THREAD

**Issue by isrjo** [pantheon-systems/wp-saml-auth#66]
You really ought to consider group to role mapping, and have the ability to deny access if no match was found. 

Just because one have been authenticated (and got valid SAML ticket) does not mean you should automatically be granted access.

**Comment by danielbachhuber** [comment]
> You really ought to consider group to role mapping, and have the ability to deny access if no match was found.

I feel reasonably confident this is possible with existing actions and filters. Have you found this not to be the case?

> Just because one have been authenticated (and got valid SAML ticket) does not mean you should automatically be granted access.

How would you suggest changing the default behavior / interpretation of the SAML response?

**Comment by isrjo** [comment]
> I feel reasonably confident this is possible with existing actions and filters. Have you found this not to be the case?

I see, so perhaps this is a mere matter of documentation ? The document I've read only states

```   /**
         * Default WordPress role to grant when provisioning new users.
         *
         * @param string
         */
        'default_role'           => get_option( 'default_role' ),
```
May I kindly as you to elaborate ?

> How would you suggest changing the default behavior / interpretation of the SAML response?

SAML is responsible for the authentication (to answer WHO) whereas this is a matter of authorization (to answer WHAT). The responsibility of authorization is the one interpreting the ticket, this wp-plugin. SAML does however help with the authorization by carrying attributes. One typically used for this is the attribute groups (but should be configurable).

In Wordpress there are by default 5 roles 
- Administrator.
- Editor.
- Author.
- Contributor.
- Subscriber.

And what I think you ought to do is to is to first have a configurable attribute for the SAML field carrying this information. ie   ```groups_attribute = 'groups'``` and secondly a mapping between group names a wordpress roles such as
- wp_role_administrator = 'my_admin_group'
- wp_role_editor = 'my_editor_group'

If not misstaken I recall this --> https://github.com/ktbartholomew/saml-20-single-sign-on
doing exactly that.

**Comment by danielbachhuber** [comment]
> May I kindly as you to elaborate ?

My bad. There wasn't a hook.

I've added a filter in #66. You can inspect the `$attributes` from the SAML response and return an error if it doesn't match your conditions:

```
/**
 * Reject authentication if $attributes doesn't include the authorized group.
 */
add_filter( 'wp_saml_auth_pre_authentication', function( $ret, $attributes ) {
	if ( empty( $attributes['group'] ) || ! in_array( 'administrators', $attributes['group'] ) ) {
		return new WP_Error( 'unauthorized-group', "Sorry, you're not a member of an authorized group." );
	}
	return $ret;
}, 10, 2 );
```

Can you verify it works for your needs? For me, it returns an error like this:

![image](https://cloud.githubusercontent.com/assets/36432/25459419/0410f81a-2a93-11e7-8b69-94f58704ba42.png)

If it meets your needs, I'll go ahead and tag a new release.

> And what I think you ought to do is to is to first have a configurable attribute for the SAML field carrying this information. ie `groups_attribute = 'groups'` and secondly a mapping between group names a wordpress roles such as

Thanks for the clarification.

It seems like the end result of what you want (validate groups in the response to specific roles) is now possible with the filter I added.

It also seems like there isn't enough of a standard for SAML groups that it makes sense to package standard configuration with this plugin. Documentation on how you can achieve different needs seems more appropriate.

Let me know what you think!

**Comment by danielbachhuber** [comment]
@isrjo Any thoughts as to whether the filter will meet your needs?
