### ISSUE TITLE
Add to Packagist

### ISSUE THREAD

**Issue by schrapel** [pantheon-systems/wp-saml-auth#73]
Can you add this repo to Packagist so we can use the version here rather than wp.org to use features like https://github.com/pantheon-systems/wp-saml-auth/commit/8c4641b2f0ffe12b61b159ca6c283828aa543298

Thanks, so much

**Comment by danielbachhuber** [comment]
@greg-1-anderson Can you submit? I get this error when I try:

![image](https://cloud.githubusercontent.com/assets/36432/26381269/7a40094a-3fd8-11e7-8dcb-1e054aac7dab.png)

**Comment by greg-1-anderson** [comment]
Done, but I can't set it to auto-update, because I don't have admin on this repository.

@danielbachhuber could you add me as a collaborator to this repository, and give me admin access?

**Comment by danielbachhuber** [comment]
@greg-1-anderson I don't have admin access to this repo either :(

**Comment by stevector** [comment]
@greg-1-anderson I made you an admin of the repo

**Comment by greg-1-anderson** [comment]
Thanks! This project has been added to Packagist and set to auto-update.

**Comment by danielbachhuber** [comment]
> This project has been added to Packagist and set to auto-update.

https://packagist.org/packages/pantheon-systems/wp-saml-auth :)

Thanks @greg-1-anderson
