### ISSUE TITLE
Provide UI to update and amend settings via plugin

### ISSUE THREAD

**Issue by mobcdi** [pantheon-systems/wp-saml-auth#80]
I understand there is the cli option for configuring the plugin but I think the provision of the UI to edit the config/filters would enhance the usability of this module especially for saml admins not familiar with wordpress but required to enable the feature

**Comment by danielbachhuber** [comment]
@mobcdi Which, say, five options do you think would be most important to make editable through the admin?

**Comment by mobcdi** [comment]
```
'simplesamlphp_autoload'
'auth_source' 
'auto_provision' 
'permit_wp_login' 
'get_user_by' 
```
to start with. At least that way you can configure working saml authentication without locking yourself or others out of the site. 
Ideally syncing the profile field would be incorporated  at some point, and then the authentication strings

**Comment by scottmckenzie** [comment]
I've added https://github.com/pantheon-systems/wp-saml-auth/pull/143 which may be suitable.
