### ISSUE TITLE
Way to specify which IDP to use

### ISSUE THREAD

**Issue by ObjectiveTruth** [pantheon-systems/wp-saml-auth#82]
Kinda new to SimpleSAMLPHP but I got everything working, however when WP redirects to SimpleSAMLPHP it shows this page, even though I only have 1 SP configured and I want to force WP to use ONLY that IDP, is there a way to specify this?

![simplesamlphp](https://i.imgur.com/cYs6OzH.png)

From the docs it says you can specify the IDP to use in the code that calls SimpleSAMLPHP but I can't seem to figure out how to do that using this plugin

https://simplesamlphp.org/docs/stable/simplesamlphp-sp

Relevant part:

> Example code:
> 
> We start off with loading a file which registers the SimpleSAMLphp classes with the autoloader.
> 
> require_once('../../lib/_autoload.php');
> 
> We select our authentication source:
> 
> $as = new SimpleSAML_Auth_Simple('default-sp');
> 
> We then require authentication:
> 
> $as->requireAuth();
> 
> And print the attributes:
> 
> $attributes = $as->getAttributes();
> print_r($attributes);
> 
> Each attribute name can be used as an index into $attributes to obtain the value. Every attribute value is an array - a single-valued attribute is an array of a single element.
> 
> We can also request authentication with a specific IdP:
> 
> $as->login(array(
>     'saml:idp' => 'https://idp.example.org/',
> ));

**Comment by danielbachhuber** [comment]
> even though I only have 1 SP configured and I want to force WP to use ONLY that IDP, is there a way to specify this?

Given the example you provided, it looks like we'd need to add a filter into WP SAML Auth so you can modify the arguments passed when instantiating SimpleSAMLphp: https://github.com/pantheon-systems/wp-saml-auth/blob/master/inc/class-wp-saml-auth.php#L184-L186

However, we'll soon be landing #68 which will let you skip SimpleSAMLphp entirely. Want to try that out?

**Comment by ObjectiveTruth** [comment]
That's even better! Any idea when approximately its set to be merged?

For now I'll leave it as SimpleSAMLPHP since I have it configured but will def take a look once its merged

**Comment by danielbachhuber** [comment]
> That's even better! Any idea when approximately its set to be merged?

Any day now, hopefully. I might even tag the release today.

> For now I'll leave it as SimpleSAMLPHP since I have it configured but will def take a look once its merged

Sounds good.

**Comment by danielbachhuber** [comment]
> I might even tag the release today.

This is now live: https://github.com/pantheon-systems/wp-saml-auth/releases/tag/v0.3.0

Feel free to open a new issue if you run into any implementation issues.

**Comment by ObjectiveTruth** [comment]
Sweeet! great work, I'll def check it out!

Also, was gonna say if you need any example libraries check out [Moodle's SAML2 Plugin](https://github.com/catalyst/moodle-auth_saml2)

**Moodle** is a learning management system built on PHP very similar to Wordpress. 

They have the same issue, in that there's a `SimpleSAMLPHP` plugin but its not very popular. However, a group of awesome devs went and built a SAML2 plugin that has no dependency on `SimpleSAMLPHP`
