### ISSUE TITLE
Role Mapping

### ISSUE THREAD

**Issue by ObjectiveTruth** [pantheon-systems/wp-saml-auth#84]
This is associated with #66 

Heya,
What I'm trying to figure out is, lets say SAML gives back an array of roles and I'd like to map those roles to Wordpress roles, there doesn't seem to be a way of doing that currently.

For example:
---
public_user => `subscriber`
random_user => `subscriber`
admin_user => `administrator`
upgraded_user => `administrator`

I see there is a `wp_saml_auth_pre_authentication` filter, but it only lets us change whether the signup process continues or not

I suggest adding a facility where you can add a mapping object and use that during the creation of the user. I'm thinking, here passing a function that gives us the attributes before inserting, and we can add `roles`

```
        'last_name_attribute' => 'last_name',
        /**
         * Default WordPress role to grant when provisioning new users.
         *
         * @param string
         */
        'default_role'           => get_option( 'default_role' ),
    );
    $value = isset( $defaults[ $option_name ] ) ? $defaults[ $option_name ] : $value;
    return $value;
```
Perhaps, adding a filter before the user gets added with the attributes and user object available?

**Comment by danielbachhuber** [comment]
> Perhaps, adding a filter before the user gets added with the attributes and user object available?

We already have a `wp_saml_auth_insert_user` filter, but it didn't include the SAML response. Would something like #85 work for you?

**Comment by ObjectiveTruth** [comment]
That's perfect! and thanks for the fast response 👍

**Comment by danielbachhuber** [comment]
> That's perfect!

Great. I've tagged a v0.3.1 release with the addition.

> and thanks for the fast response

Happy to help!
