### ISSUE TITLE
Make the plugin work with Google as SAML provider: do not require signOff url

### ISSUE THREAD

**Issue by koyan** [pantheon-systems/wp-saml-auth#92]
When you setup google as SAML provider, google provides the 3 of the required info (entityID, signOnUrl, key) but does not provide the fourth (signOffUrl). If you try to setup the plugin (on the "internal" method) without the signOff url, you get an error when you logout.

**Comment by danielbachhuber** [comment]
Hi @koyan,

Can you share steps to reproduce and the error you see?
