### ISSUE TITLE
Include the generated autoload files in your git

### ISSUE THREAD

**Issue by koyan** [pantheon-systems/wp-saml-auth#93]
Currently the .gitignore has the following line: 
`/vendor/`
in it, making it ignore the autoload files that are autogenerated via composer update. 
But this means that the plugin cannot be installed via composer (without adding an extra step of running `composer update` on the plugin directory itself). 
This makes automatic deployment of the plugin more complicated. 
I believe the solution would be to replace it with: 
```
vendor/*
!vendor/composer
!vendor/autoload.php
```
(haven't tested it though)

**Comment by danielbachhuber** [comment]
Hi @koyan:

> But this means that the plugin cannot be installed via composer (without adding an extra step of running `composer update` on the plugin directory itself).

I suspect you may be using Composer incorrectly. If the plugin is added as a dependency of a Composer project, then all of its dependencies should be installed through that parent project.
