### ISSUE TITLE
Make the plugin installable without the need for code changes in the theme

### ISSUE THREAD

**Issue by koyan** [pantheon-systems/wp-saml-auth#94]
For the "internal" method, currently to install the plugin you need to do code changes (to pass the required data). 
This presents various problems: 
- You cannot deploy using publicly open repositories (because then you would expose the entityID, signonURL etc to the public). 
- You cannot deploy multipe environments with the same code

Solution would be to have that data pass from the administration (settings of the plugin).

**Comment by danielbachhuber** [comment]
Hi @koyan,

This is already tracked in #80

> You cannot deploy using publicly open repositories (because then you would expose the entityID, signonURL etc to the public).

The more correct implementation would be to expose the secrets via environment variable or constants that are defined in some secret manner.

> You cannot deploy multipe environments with the same code

Similarly, your secrets management implementation could conditionally serve different configuration dependent on environment.
