### ISSUE TITLE
Make the plugin not fail if no data (entityID, signonURL, key) get passed to it

### ISSUE THREAD

**Issue by koyan** [pantheon-systems/wp-saml-auth#95]
Currently, if no data are passed to the plugin (entityID, signonURL, key) it fails, throwing an error. 
This should be handled and not give an error, just ignore the plugin.

**Comment by danielbachhuber** [comment]
> Currently, if no data are passed to the plugin (entityID, signonURL, key) it fails, throwing an error.

Can you share the error you're seeing?
