### ISSUE TITLE
Fully support PHP 7.1 

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp-saml-auth#98]
mcrypt is deprecated in PHP 7.1

Creating this issue to track the resolution of https://github.com/onelogin/php-saml/issues/255

**Comment by danielbachhuber** [comment]
mcrypt can be installed against PHP 7.2 with `pecl install channel://pecl.php.net/mcrypt-1.0.1`

**Comment by defunctl** [comment]
Hey Daniel,

With One Login's PHP-SAML version at 3.0 now supporting 7.1/no mcrypt, any plans to update this WP Saml Auth to support it?

**Comment by danielbachhuber** [comment]
> With One Login's PHP-SAML version at 3.0 now supporting 7.1/no mcrypt, any plans to update this WP Saml Auth to support it?

Yep, we can do so in the next couple of weeks. I wanted to wait and make sure there wasn't a 3.0.1 and 3.0.2
